### ISSUE TITLE
Compatibility with 2.3.15

### ISSUE THREAD

**Issue by brunofjesus** [lmatte7/goMesh#7]
First of all thanks for this awesome package!
I noticed that it stopped working after I upgraded my devices from 2.3.13 to 2.3.15, I tried using the latest protobufs but it still does not work, I don't know what changed in the latest version in order for it to break this lib.

Here is my fork, it has the protobuf update and also other small changes that I was doing before:
https://github.com/brunofjesus/goMesh

The protobufs were generated against this version https://github.com/meshtastic/protobufs/commits/v2.3.15

**Comment by lmatte7** [comment]
Thank you for the heads up! I don't have a good way to subscribe to breaking changes beyond manually monitoring the releases, so the information is much appreciated. 

Did you notice if there were any commands in particular that were broken (or ones that still worked)? Knowing that will save me some time investigating what all needs to be updated to cut a new release

**Comment by brunofjesus** [comment]
I just did some testing with the CLI tool: https://github.com/lmatte7/meshtastic-go

The info command does not work properly, if I keep running the info command in a loop it sometimes gets the info while the device is on the meshtastic boot logo.
I can send and receive messages just fine.

**Comment by brunofjesus** [comment]
I investigated a bit and turns out that the device is actually sending the node info messages back, but it looks like the library does not wait for all the responses. Maybe this last meshtastic versions are slower?
It "worked" with this nasty hack (https://github.com/brunofjesus/goMesh/commit/d09c3b4f6b59d943f09819665552ce42c770cde6), 

I'm still a newbie in meshtastic, but maybe we should keep reading the responses until we get a Payload with a desired type?

**Comment by lmatte7** [comment]
I've pushed a new [version](https://github.com/lmatte7/goMesh/releases/tag/v0.2.0) (`0.2.0`) that includes a fix for the issues you mentioned here. Thank you for the information and the test code! Sorry for the (way longer than I thought it would be 😂) delay. 

I'm going to mark this as closed, but feel free to re-open it or file another issue if you find anything else wrong
